#这里配置一个加密的密钥
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7

#使用加密了的配置
#test:
#  datasource:
#    username: ENC(MncHf2ANrI7ecelmdnHmzg==)
#    password: ENC(vQPa96fd5XhDzpj2ktHRvQ==)

#这里配置mysql数据库连接配置文件
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_springboot
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver